version: '2'
services:
    ###################################################################
    correlator:
        #image: docker.elastic.co/logstash/logstash-oss:6.0.0
        image: truthadjustr/siemcorr:latest
        container_name: corel
        volumes:
            - ./correlator/recognizer.conf:/recognizer.conf
        command: ["/usr/share/logstash/bin/logstash","-r","-f","/recognizer.conf"]
        links:
            - cache
        ports:
            - 5140:5140/udp
    ###################################################################
    cache:
        image: redis:latest
        container_name: cache
    ###################################################################
    siemprocwlclogin:
        image: truthadjustr/siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwlclogin
        volumes:
            - ./pyhandlers/siemprocwlclogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - t252snmpagent
    ###################################################################
    siemprocwindowslogin:
        image: truthadjustr/siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwindowslogin
        volumes:
            - ./pyhandlers/siemprocwindowslogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - t252snmpagent
    ###################################################################
    siemprocrogueap:
        image: truthadjustr/siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocrogueap
        volumes:
            - ./pyhandlers/siemprocrogueap.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - t252snmpagent
    ###################################################################
    siemprocjamming:
        image: truthadjustr/siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocjamming
        volumes:
            - ./pyhandlers/siemprocjamming.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - t252snmpagent
    ###################################################################
    siemprocwlcradiuslogin:
        image: truthadjustr/siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwlcradiuslogin
        volumes:
            - ./pyhandlers/siemprocwlcradiuslogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - t252snmpagent
    ###################################################################
    t252snmpagent:
        image: truthadjustr/t252snmpagent:latest
        #COPY t252snmpagent/entrypoint.sh /
        #COPY t252snmpagent/siemevent.py /root/
        container_name: t252snmpagent
        volumes:
            - ./var.siem:/var/siem
            - ./t252snmpagent/:/root/
            - ./t252snmpagent/entrypoint.sh:/entrypoint.sh
        ports:
            - 1610:161/udp 
        links:
            - cache
