version: '2'
services:
    ###################################################################
    correlator:
        image: docker.elastic.co/logstash/logstash-oss:6.0.0
        container_name: corel
        volumes:
            - ./correlator/recognizer.conf:/recognizer.conf
        command: ["/usr/share/logstash/bin/logstash","-r","-f","/recognizer.conf"]
        links:
            - cache
        ports:
            - 5140:5140/udp
    ###################################################################
    cache:
        image: redis:latest
        container_name: cache
    ###################################################################
    siemprocwlclogin:
        image: siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwlclogin
        volumes:
            - ./pyhandlers/siemprocwlclogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - snmpsim
    ###################################################################
    siemprocwindowslogin:
        image: siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwindowslogin
        volumes:
            - ./pyhandlers/siemprocwindowslogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - snmpsim
    ###################################################################
    siemprocrogueap:
        image: siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocrogueap
        volumes:
            - ./pyhandlers/siemprocrogueap.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - snmpsim
    ###################################################################
    siemprocjamming:
        image: siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocjamming
        volumes:
            - ./pyhandlers/siemprocjamming.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - snmpsim
    ###################################################################
    siemprocwlcradiuslogin:
        image: siempy:latest
        environment:
            - PYTHONUNBUFFERED=1
        container_name: siemprocwlcradiuslogin
        volumes:
            - ./pyhandlers/siemprocwlcradiuslogin.py:/mainapp.py
            - ./pyhandlers/libs:/libs
        links:
            - cache
            - snmpsim
    ###################################################################
    snmpsim:
        image: tandrup/snmpsim:latest
        container_name: snmpsim
        volumes:
            - ./snmpsimdata:/usr/share/snmpsim/data
        ports:
            - 1610:161/udp 
